// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Nav$ReactHooksTemplate = require("./Nav.bs.js");

function App(Props) {
  return React.createElement("section", {
              className: ""
            }, React.createElement(Nav$ReactHooksTemplate.make, { }), React.createElement("h1", undefined, "Hello there"));
}

var make = App;

exports.make = make;
/* react Not a pure module */
