// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function str(prim) {
  return prim;
}

function useState(initial) {
  return React.useReducer((function (_ignored, newState) {
                return newState;
              }), initial);
}

exports.str = str;
exports.useState = useState;
/* react Not a pure module */
