// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Post$ReactHooksTemplate = require("./Post.bs.js");
var Helpers$ReactHooksTemplate = require("./Helpers.bs.js");

function Nav(Props) {
  var posts = Props.posts;
  var match = Helpers$ReactHooksTemplate.useState(true);
  var setOpen = match[1];
  Helpers$ReactHooksTemplate.useState("");
  return React.createElement("nav", {
              className: Belt_List.reduce(/* :: */[
                    "nav",
                    /* :: */[
                      match[0] ? "nav--open" : "",
                      /* [] */0
                    ]
                  ], "", (function (acc, x) {
                      return acc + (" " + x);
                    }))
            }, React.createElement("form", {
                  action: "",
                  onSubmit: (function (e) {
                      e.preventDefault();
                      return /* () */0;
                    })
                }, React.createElement("input", {
                      "aria-label": "posts search",
                      className: "nav__form__input",
                      placeholder: "Search",
                      type: "text"
                    }), React.createElement("button", {
                      className: "nav__form__burger",
                      onClick: (function (e) {
                          e.preventDefault();
                          return Curry._1(setOpen, false);
                        })
                    }, Helpers$ReactHooksTemplate.str("X"))), React.createElement("ol", {
                  className: "nav__results"
                }, Belt_Array.mapWithIndex($$Array.of_list(posts), (function (i, p) {
                        return React.createElement("li", {
                                    key: String(i),
                                    className: "nav__results__item"
                                  }, React.createElement(Post$ReactHooksTemplate.Header[/* small */0], {
                                        post: p
                                      }));
                      }))));
}

var make = Nav;

exports.make = make;
/* react Not a pure module */
