// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Post$ReactHooksTemplate = require("./Post.bs.js");
var Helpers$ReactHooksTemplate = require("./Helpers.bs.js");

function Nav(Props) {
  var ph_post = /* record */[
    /* id */0,
    /* author */"cat",
    /* date */"2019-06-22",
    /* title */"Cats Should Rule The World, Soon",
    /* body */"Sure they will, the question is - when?"
  ];
  var match = React.useReducer((function (state, action) {
          return /* record */[
                  /* posts */List.merge((function (l1, l2) {
                          return l1[/* id */0] - l2[/* id */0] | 0;
                        }), state[/* posts */0], action[0]),
                  /* search */state[/* search */1]
                ];
        }), /* record */[
        /* posts : :: */[
          ph_post,
          /* :: */[
            ph_post,
            /* :: */[
              ph_post,
              /* [] */0
            ]
          ]
        ],
        /* search */""
      ]);
  return React.createElement("nav", {
              className: "nav"
            }, React.createElement("input", {
                  className: "nav__input",
                  placeholder: "Search",
                  type: "text"
                }), React.createElement("button", {
                  className: "nav__burger"
                }, Helpers$ReactHooksTemplate.str("X")), React.createElement("ol", {
                  className: "nav__results"
                }, Belt_Array.mapWithIndex($$Array.of_list(match[0][/* posts */0]), (function (i, p) {
                        return React.createElement("li", {
                                    key: String(i),
                                    className: "nav__results__item"
                                  }, React.createElement(Post$ReactHooksTemplate.Header[/* small */0], {
                                        post: p
                                      }));
                      }))));
}

var make = Nav;

exports.make = make;
/* react Not a pure module */
