// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Helpers$ReactHooksTemplate = require("./Helpers.bs.js");

function Post$Header$small(Props) {
  var post = Props.post;
  var style = ReactDOMRe.Style[/* unsafeAddProp */1](ReactDOMRe.Style[/* unsafeAddProp */1]({ }, "--align", "left"), "--size", "0.75");
  return React.createElement("div", {
              className: "header header--small",
              style: style
            }, React.createElement("h1", {
                  className: "header__text"
                }, Helpers$ReactHooksTemplate.str(post[/* title */3])), React.createElement("div", {
                  className: "header__bottom"
                }, React.createElement("span", {
                      className: "header__bottom__author"
                    }, Helpers$ReactHooksTemplate.str(post[/* author */1])), React.createElement("time", {
                      className: "header__bottom__date"
                    }, Helpers$ReactHooksTemplate.str(post[/* date */2]))));
}

function Post$Header(Props) {
  var post = Props.post;
  return React.createElement("div", {
              className: "header"
            }, React.createElement("h1", {
                  className: "header__text"
                }, Helpers$ReactHooksTemplate.str(post[/* title */3])), React.createElement("div", {
                  className: "header__bottom"
                }, React.createElement("span", {
                      className: "header__bottom__author"
                    }, Helpers$ReactHooksTemplate.str(post[/* author */1])), React.createElement("time", {
                      className: "header__bottom__date"
                    }, Helpers$ReactHooksTemplate.str(post[/* date */2]))));
}

var Header = /* module */[
  /* small */Post$Header$small,
  /* make */Post$Header
];

function Post(Props) {
  var post = Props.post;
  return React.createElement("article", undefined, React.createElement(Post$Header, {
                  post: post
                }));
}

var make = Post;

exports.Header = Header;
exports.make = make;
/* react Not a pure module */
